insert into public.tb_raca (nm_raca) values ('Desert spiny lizard');
insert into public.tb_raca (nm_raca) values ('Bahama pintail');
insert into public.tb_raca (nm_raca) values ('Two-toed sloth');
insert into public.tb_raca (nm_raca) values ('Red-billed buffalo weaver');
insert into public.tb_raca (nm_raca) values ('Eagle owl (unidentified)');
insert into public.tb_raca (nm_raca) values ('Dove, emerald-spotted wood');
insert into public.tb_raca (nm_raca) values ('Roller, lilac-breasted');
insert into public.tb_raca (nm_raca) values ('Two-toed tree sloth');
insert into public.tb_raca (nm_raca) values ('Tortoise, galapagos');
insert into public.tb_raca (nm_raca) values ('Raccoon dog');
insert into public.tb_raca (nm_raca) values ('Giant otter');
insert into public.tb_raca (nm_raca) values ('African snake (unidentified)');
insert into public.tb_raca (nm_raca) values ('Gerenuk');
insert into public.tb_raca (nm_raca) values ('Grenadier, purple');
insert into public.tb_raca (nm_raca) values ('Chimpanzee');
insert into public.tb_raca (nm_raca) values ('Bustard, stanley');
insert into public.tb_raca (nm_raca) values ('Yellow-headed caracara');
insert into public.tb_raca (nm_raca) values ('Red squirrel');
insert into public.tb_raca (nm_raca) values ('Puma, south american');
insert into public.tb_raca (nm_raca) values ('Black and white colobus');

insert into public.tb_especie (nm_especie) values ('Hyaena brunnea');
insert into public.tb_especie (nm_especie) values ('Columba palumbus');
insert into public.tb_especie (nm_especie) values ('Canis mesomelas');
insert into public.tb_especie (nm_especie) values ('Gazella granti');
insert into public.tb_especie (nm_especie) values ('Heloderma horridum');
insert into public.tb_especie (nm_especie) values ('Oryx gazella callotis');
insert into public.tb_especie (nm_especie) values ('Cervus duvauceli');
insert into public.tb_especie (nm_especie) values ('Terrapene carolina');
insert into public.tb_especie (nm_especie) values ('Irania gutteralis');
insert into public.tb_especie (nm_especie) values ('Phascogale calura');
